affinity: {}

app: {
  ADMIN_EMAIL: "webmaster@raddcreative.io",
  APP_NAME: "CIP 1694",
  APP_ENV: "production",
  APP_DEBUG: "false",
  APP_SETUP: "false",
  APP_URL: "https://www.1694.io"
}

certmanager:
  issuer: letsencrypt-prod-issuer
  email: webmaster@1694.io
  server: https://acme-staging-v02.api.letsencrypt.org/directory

certificate:
  secretName: www-1694-tls
  hosts:
    - "'*.1694.io'"

secret:
  NEXT_PUBLIC_GOOGLE_API:

image:
  repository: registry.lidonation.com/voltaire/www.1694.io
  tag: stable
  pullPolicy: IfNotPresent
  pullSecret: '1694-registry-deploy-token'

imageCredentials:
  registry: registry.raddcreative.io
  username: someone
  password: sillyness
  email: webmaster@1694.io

ingress:
  enabled: true
  controller:
    headers:
      HTTPS: "on"
  annotations: {
    kubernetes.io/ingress.class: traefik,
    cert-manager.io/cluster-issuer: letsencrypt-issuer,
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure,web",
    traefik.ingress.kubernetes.io/router.middlewares: "traefik-redirect-http-to-https@kubernetescrd,traefik-default-headers@kubernetescrd"
  }
  path: "/"
  hosts:
    - www.1694.io
  tls:
    - secretName: www-1694-tls
      hosts:
        - www.1694.io
        - 1694.io

labels:
  domain: 1694.io
  service: web

namespace: voltaire

nodeSelector: {}

persistence:
  size: 10Gi
  storageClass: longhorn
  accessMode: ReadWriteMany
  subPath: "uploads"
  mountPath: "/app/uploads"

redis:
  image: redis:7.2-rc2-alpine

replicaCount: 2

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 1024Mi
    cpu: 300m

serviceAccount:
  create: true

service:
  type: ClusterIP
  port: 80

