FROM node:20-alpine 

WORKDIR /app

RUN yarn install --frozen-lockfile yarn --frozen-lockfile && yarn remove @emurgo/cardano-serialization-lib-asmjs && yarn add @emurgo/cardano-serialization-lib-asmjs@12.0.0-beta.1 && yarn list --pattern  @emurgo/cardano-serialization-lib-asmjs

EXPOSE 3000

CMD ["npx","--max-old-space-size=8192", "next", "dev"]