FROM node:20-alpine 

WORKDIR /app

RUN yarn install --frozen-lockfile && yarn add @emurgo/cardano-serialization-lib-asmjs@12.0.0-beta.1

EXPOSE 3000

CMD ["npx","--max-old-space-size=8192", "next", "dev"]