version: "3"
services:
  backend:
    container_name: backend # Name of the backend container
    build: # Build configuration for the backend
      context: ./backend # Directory containing Dockerfile
      dockerfile: Dockerfile.dev
    image: io-1694:latest # Use the latest io-1694 image
    restart: unless-stopped # Always restart unless explicitly stopped
    environment: # Environment variables for configuration
      HOST: 0.0.0.0
      PORT: 8080
      DATABASE_HOST: database # Link to the database service by name
      DATABASE_NAME: pdf_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      NODE_ENV: development # Set node environment to development
    volumes: # Mount points for persistent data and source code
      - "./backend:/app"
    ports:
      - "8080:8080" # Expose port 8080 to the host
    networks:
      - io-1694 # Connect to the 'io-1694' network
    depends_on:
      - database # Depends on the database service
  database:
    container_name: database # Name of the database container
    platform: linux/arm64 # Specify the platform (important for ARM64 architectures)
    image: postgres:12.0-alpine # Use PostgreSQL 12 on Alpine for smaller size
    restart: unless-stopped
    environment: # PostgreSQL user, password, and database name
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pdf_db
    volumes:
      - db-data:/var/lib/postgresql/data/ # Persistent storage for the database
    networks:
      - io-1694 # Connect to the 'io-1694' network
  frontend:
    container_name: frontend # Name of the frontend container
    build: # Build configuration for the frontend
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000 # Environment variable for the API URL
    ports:
      - "4000:3000" # Expose port 4000 to the host
    networks:
      - io-1694
    volumes:
      - "./frontend:/app"
    depends_on:
      - backend # Depends on the backend service
  cardano-node:
    image: ghcr.io/intersectmbo/cardano-node:8.9.0
    command: [
      "run",
      "--config", "/config/config.json",
      "--database-path", "/data/db",
      "--socket-path", "/ipc/node.socket",
      "--topology", "/config/topology.json"
    ]
    volumes:
      - ./cardanonode/config/network/${NETWORK:-sanchonet}/cardano-node:/config
      - ./cardanonode/config/network/${NETWORK:-sanchonet}/genesis:/genesis
      - node-db:/data
      - node-ipc:/ipc
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
volumes:
  db-data:
  node-db:
  node-ipc:
networks:
  io-1694:
    driver: bridge
