apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ $.Chart.Name }}-secrets"
  namespace: {{ .Values.namespace }}
stringData:
  NEXT_PUBLIC_GOOGLE_API: {{ .Values.secrets.NEXT_PUBLIC_GOOGLE_API}}