apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ $.Chart.Name }}-queue-secrets"
  namespace: {{ .Values.namespace }}
data:
  {{ range .Files.Lines "queue_env" }}
  {{   if and . (not (hasPrefix "#" .)) (contains "=" .) }}
  {{     $parts := regexSplit "=" . 2 }}
  {{     include "www-1694.ipfs.rejectEnvKey" (dict "key" (index $parts 0) "file" "queue_env") }}
  {{     index $parts 0 }}: {{ index $parts 1 | b64enc }}
  {{   end }}
  {{ end }}
