{{- $ipfs := .Values.ipfs | default dict }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ $.Chart.Name }}-backend-secrets"
  namespace: {{ .Values.namespace }}
data:
  {{ range .Files.Lines "backend_env" }}
  {{   if and . (not (hasPrefix "#" .)) (contains "=" .) }}
  {{     $parts := regexSplit "=" . 2 }}
  {{     include "www-1694.ipfs.rejectEnvKey" (dict "key" (index $parts 0) "file" "backend_env") }}
  {{     index $parts 0 }}: {{ index $parts 1 | b64enc }}
  {{   end }}
  {{ end }}
  IPFS_CLUSTER_API_URL: {{ required "ipfs.clusterApiUrl is not set" $ipfs.clusterApiUrl | b64enc }}
  IPFS_CLUSTER_API_USER: {{ required "ipfs.clusterApiUser is not set" $ipfs.clusterApiUser | b64enc }}
  IPFS_CLUSTER_API_PASSWORD: {{ required "ipfs.clusterApiPassword is not set" $ipfs.clusterApiPassword | b64enc }}
  IPFS_GATEWAY_URL: {{ required "ipfs.gatewayUrl is not set" $ipfs.gatewayUrl | b64enc }}
