apiVersion: v1
kind: Service
metadata:
  name: "{{ $.Chart.Name }}-queue-service"
  namespace: {{ .Values.namespace }}
  labels:
    service: "{{ .Values.queue.labels.service }}"
  annotations:
    traefik.ingress.kubernetes.io/affinity: "false"
spec:
  ports:
    - port: 80
      name: queue
      targetPort: queue
      protocol: TCP
  selector:
    service: "{{ .Values.queue.labels.service }}"
