export const QUERY_KEYS = {
  getAdaHolderCurrentDelegationKey: 'getAdaHolderCurrentDelegationKey',
  getNotesKey: 'getAllNotesKey',
  getSingleDRepKey: 'getSingleDRepKey',
  getAllDRepsKey: 'getAllDRepsKey',
  getDRepStatsKey: 'getDRepStatsKey',
  getDRepTimelineKey: 'getDRepTimelineKey',
  getDrepDelegators: 'getDrepDelegators',
  getVoterGovActions: 'getVoterGovActions',
  getDRepMetadataKey: 'getDRepMetadataKey',
  getActionsProposalsKey: 'getActionsProposalsKey',
  getActionProposalKey: 'getActionProposalKey',
  getActionProposalCommentsKey: 'getActionProposalCommentsKey',
  getActionProposalPollKey: 'getActionProposalPollKey',
  getDRepRegStatusKey: 'getDRepRegStatusKey',
  getUserProposalVoteKey: 'getUserProposalVoteKey',
  pollVotesKey: 'pollVotesKey',
};
