// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Index": {
    "title": "Voltaire DRep Campaign Module"
  }
};
export default messages;